/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-26 at 21:55:50 UTC 
 * Modify at your own risk.
 */

package com.debdroid.apiwithjdo.dao.employeeendpoint.model;

/**
 * Model definition for Employee.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the employeeendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Employee extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String deg;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long eid;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ename;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double salary;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDeg() {
    return deg;
  }

  /**
   * @param deg deg or {@code null} for none
   */
  public Employee setDeg(java.lang.String deg) {
    this.deg = deg;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getEid() {
    return eid;
  }

  /**
   * @param eid eid or {@code null} for none
   */
  public Employee setEid(java.lang.Long eid) {
    this.eid = eid;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEname() {
    return ename;
  }

  /**
   * @param ename ename or {@code null} for none
   */
  public Employee setEname(java.lang.String ename) {
    this.ename = ename;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getSalary() {
    return salary;
  }

  /**
   * @param salary salary or {@code null} for none
   */
  public Employee setSalary(java.lang.Double salary) {
    this.salary = salary;
    return this;
  }

  @Override
  public Employee set(String fieldName, Object value) {
    return (Employee) super.set(fieldName, value);
  }

  @Override
  public Employee clone() {
    return (Employee) super.clone();
  }

}
