/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-26 at 21:55:50 UTC 
 * Modify at your own risk.
 */

package com.debdroid.apiwithjdo.dao.employeeendpoint;

/**
 * Service definition for Employeeendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link EmployeeendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Employeeendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the employeeendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  //public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";
  //public static final String DEFAULT_ROOT_URL = "http://10.0.2.2:8888/_ah/api/";
  public static final String DEFAULT_ROOT_URL = "https://1-dot-euphoric-truth-93312.appspot.com/_ah/api/";
  
  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "employeeendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Employeeendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Employeeendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getEmployee".
   *
   * This request holds the parameters needed by the employeeendpoint server.  After setting any
   * optional parameters, call the {@link GetEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetEmployee getEmployee(java.lang.Long id) throws java.io.IOException {
    GetEmployee result = new GetEmployee(id);
    initialize(result);
    return result;
  }

  public class GetEmployee extends EmployeeendpointRequest<com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee> {

    private static final String REST_PATH = "employee/{id}";

    /**
     * Create a request for the method "getEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link GetEmployee#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetEmployee#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetEmployee(java.lang.Long id) {
      super(Employeeendpoint.this, "GET", REST_PATH, null, com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetEmployee setAlt(java.lang.String alt) {
      return (GetEmployee) super.setAlt(alt);
    }

    @Override
    public GetEmployee setFields(java.lang.String fields) {
      return (GetEmployee) super.setFields(fields);
    }

    @Override
    public GetEmployee setKey(java.lang.String key) {
      return (GetEmployee) super.setKey(key);
    }

    @Override
    public GetEmployee setOauthToken(java.lang.String oauthToken) {
      return (GetEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public GetEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetEmployee setQuotaUser(java.lang.String quotaUser) {
      return (GetEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetEmployee setUserIp(java.lang.String userIp) {
      return (GetEmployee) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetEmployee setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetEmployee set(String parameterName, Object value) {
      return (GetEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertEmployee".
   *
   * This request holds the parameters needed by the employeeendpoint server.  After setting any
   * optional parameters, call the {@link InsertEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee}
   * @return the request
   */
  public InsertEmployee insertEmployee(com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee content) throws java.io.IOException {
    InsertEmployee result = new InsertEmployee(content);
    initialize(result);
    return result;
  }

  public class InsertEmployee extends EmployeeendpointRequest<com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee> {

    private static final String REST_PATH = "employee";

    /**
     * Create a request for the method "insertEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link InsertEmployee#execute()} method to invoke the remote
     * operation. <p> {@link InsertEmployee#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee}
     * @since 1.13
     */
    protected InsertEmployee(com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee content) {
      super(Employeeendpoint.this, "POST", REST_PATH, content, com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee.class);
    }

    @Override
    public InsertEmployee setAlt(java.lang.String alt) {
      return (InsertEmployee) super.setAlt(alt);
    }

    @Override
    public InsertEmployee setFields(java.lang.String fields) {
      return (InsertEmployee) super.setFields(fields);
    }

    @Override
    public InsertEmployee setKey(java.lang.String key) {
      return (InsertEmployee) super.setKey(key);
    }

    @Override
    public InsertEmployee setOauthToken(java.lang.String oauthToken) {
      return (InsertEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertEmployee setQuotaUser(java.lang.String quotaUser) {
      return (InsertEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertEmployee setUserIp(java.lang.String userIp) {
      return (InsertEmployee) super.setUserIp(userIp);
    }

    @Override
    public InsertEmployee set(String parameterName, Object value) {
      return (InsertEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listByDesignation".
   *
   * This request holds the parameters needed by the employeeendpoint server.  After setting any
   * optional parameters, call the {@link ListByDesignation#execute()} method to invoke the remote
   * operation.
   *
   * @param designation
   * @return the request
   */
  public ListByDesignation listByDesignation(java.lang.String designation) throws java.io.IOException {
    ListByDesignation result = new ListByDesignation(designation);
    initialize(result);
    return result;
  }

  public class ListByDesignation extends EmployeeendpointRequest<com.debdroid.apiwithjdo.dao.employeeendpoint.model.EmployeeCollection> {

    private static final String REST_PATH = "employeecollection/{Designation}";

    /**
     * Create a request for the method "listByDesignation".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link ListByDesignation#execute()} method to invoke the remote
     * operation. <p> {@link ListByDesignation#initialize(com.google.api.client.googleapis.services.Ab
     * stractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param designation
     * @since 1.13
     */
    protected ListByDesignation(java.lang.String designation) {
      super(Employeeendpoint.this, "GET", REST_PATH, null, com.debdroid.apiwithjdo.dao.employeeendpoint.model.EmployeeCollection.class);
      this.designation = com.google.api.client.util.Preconditions.checkNotNull(designation, "Required parameter designation must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListByDesignation setAlt(java.lang.String alt) {
      return (ListByDesignation) super.setAlt(alt);
    }

    @Override
    public ListByDesignation setFields(java.lang.String fields) {
      return (ListByDesignation) super.setFields(fields);
    }

    @Override
    public ListByDesignation setKey(java.lang.String key) {
      return (ListByDesignation) super.setKey(key);
    }

    @Override
    public ListByDesignation setOauthToken(java.lang.String oauthToken) {
      return (ListByDesignation) super.setOauthToken(oauthToken);
    }

    @Override
    public ListByDesignation setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListByDesignation) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListByDesignation setQuotaUser(java.lang.String quotaUser) {
      return (ListByDesignation) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListByDesignation setUserIp(java.lang.String userIp) {
      return (ListByDesignation) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key("Designation")
    private java.lang.String designation;

    /**

     */
    public java.lang.String getDesignation() {
      return designation;
    }

    public ListByDesignation setDesignation(java.lang.String designation) {
      this.designation = designation;
      return this;
    }

    @Override
    public ListByDesignation set(String parameterName, Object value) {
      return (ListByDesignation) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listEmployee".
   *
   * This request holds the parameters needed by the employeeendpoint server.  After setting any
   * optional parameters, call the {@link ListEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListEmployee listEmployee() throws java.io.IOException {
    ListEmployee result = new ListEmployee();
    initialize(result);
    return result;
  }

  public class ListEmployee extends EmployeeendpointRequest<com.debdroid.apiwithjdo.dao.employeeendpoint.model.CollectionResponseEmployee> {

    private static final String REST_PATH = "employee";

    /**
     * Create a request for the method "listEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link ListEmployee#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListEmployee#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListEmployee() {
      super(Employeeendpoint.this, "GET", REST_PATH, null, com.debdroid.apiwithjdo.dao.employeeendpoint.model.CollectionResponseEmployee.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListEmployee setAlt(java.lang.String alt) {
      return (ListEmployee) super.setAlt(alt);
    }

    @Override
    public ListEmployee setFields(java.lang.String fields) {
      return (ListEmployee) super.setFields(fields);
    }

    @Override
    public ListEmployee setKey(java.lang.String key) {
      return (ListEmployee) super.setKey(key);
    }

    @Override
    public ListEmployee setOauthToken(java.lang.String oauthToken) {
      return (ListEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public ListEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListEmployee setQuotaUser(java.lang.String quotaUser) {
      return (ListEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListEmployee setUserIp(java.lang.String userIp) {
      return (ListEmployee) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListEmployee setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListEmployee setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListEmployee set(String parameterName, Object value) {
      return (ListEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeEmployee".
   *
   * This request holds the parameters needed by the employeeendpoint server.  After setting any
   * optional parameters, call the {@link RemoveEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveEmployee removeEmployee(java.lang.Long id) throws java.io.IOException {
    RemoveEmployee result = new RemoveEmployee(id);
    initialize(result);
    return result;
  }

  public class RemoveEmployee extends EmployeeendpointRequest<Void> {

    private static final String REST_PATH = "employee/{id}";

    /**
     * Create a request for the method "removeEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link RemoveEmployee#execute()} method to invoke the remote
     * operation. <p> {@link RemoveEmployee#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveEmployee(java.lang.Long id) {
      super(Employeeendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveEmployee setAlt(java.lang.String alt) {
      return (RemoveEmployee) super.setAlt(alt);
    }

    @Override
    public RemoveEmployee setFields(java.lang.String fields) {
      return (RemoveEmployee) super.setFields(fields);
    }

    @Override
    public RemoveEmployee setKey(java.lang.String key) {
      return (RemoveEmployee) super.setKey(key);
    }

    @Override
    public RemoveEmployee setOauthToken(java.lang.String oauthToken) {
      return (RemoveEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveEmployee setQuotaUser(java.lang.String quotaUser) {
      return (RemoveEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveEmployee setUserIp(java.lang.String userIp) {
      return (RemoveEmployee) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveEmployee setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveEmployee set(String parameterName, Object value) {
      return (RemoveEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateEmployee".
   *
   * This request holds the parameters needed by the employeeendpoint server.  After setting any
   * optional parameters, call the {@link UpdateEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee}
   * @return the request
   */
  public UpdateEmployee updateEmployee(com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee content) throws java.io.IOException {
    UpdateEmployee result = new UpdateEmployee(content);
    initialize(result);
    return result;
  }

  public class UpdateEmployee extends EmployeeendpointRequest<com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee> {

    private static final String REST_PATH = "employee";

    /**
     * Create a request for the method "updateEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link UpdateEmployee#execute()} method to invoke the remote
     * operation. <p> {@link UpdateEmployee#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee}
     * @since 1.13
     */
    protected UpdateEmployee(com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee content) {
      super(Employeeendpoint.this, "PUT", REST_PATH, content, com.debdroid.apiwithjdo.dao.employeeendpoint.model.Employee.class);
    }

    @Override
    public UpdateEmployee setAlt(java.lang.String alt) {
      return (UpdateEmployee) super.setAlt(alt);
    }

    @Override
    public UpdateEmployee setFields(java.lang.String fields) {
      return (UpdateEmployee) super.setFields(fields);
    }

    @Override
    public UpdateEmployee setKey(java.lang.String key) {
      return (UpdateEmployee) super.setKey(key);
    }

    @Override
    public UpdateEmployee setOauthToken(java.lang.String oauthToken) {
      return (UpdateEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateEmployee setQuotaUser(java.lang.String quotaUser) {
      return (UpdateEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateEmployee setUserIp(java.lang.String userIp) {
      return (UpdateEmployee) super.setUserIp(userIp);
    }

    @Override
    public UpdateEmployee set(String parameterName, Object value) {
      return (UpdateEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Employeeendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Employeeendpoint}. */
    @Override
    public Employeeendpoint build() {
      return new Employeeendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link EmployeeendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setEmployeeendpointRequestInitializer(
        EmployeeendpointRequestInitializer employeeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(employeeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
